Spawn:
  World: world
  X: 0
  Y: 0
  Z: 0
  Pitch: 0
  Yaw: 0
  Set: false

challonge:
  username: ""
  api-key: ""

TournamentSpawn:
  World: tournament
  X: 0
  Y: 0
  Z: 0
  Pitch: 0
  Yaw: 0
  Set: false

BoatRace:
  World: tournament
  X: 0
  Y: 0
  Z: 0
  Pitch: 0
  Yaw: 0
  Set: false