name: JadedDuels
version: '${project.version}'
main: net.jadedmc.jadedduels.JadedDuelsPlugin
api-version: 1.20

depend:
  - JadedCore
  - JadedChat
  - PlaceholderAPI

commands:
  arena:
    description: Runs the arena command.
  testgame:
    description: Test game
  kits:
    description: View the available kits.
  create:
    description: create tournament.
  start:
    description: start tournament.
  tournament:
    description: teleport to tournament.