name: JadedDuels
version: '${project.version}'
main: net.jadedmc.jadedduels.JadedDuelsPlugin
api-version: 1.20

depend:
  - JadedCore
  - JadedChat
  - PlaceholderAPI

commands:
  arena:
    description: Runs the arena command.
    permission: duels.admin
  create:
    description: create tournament.
    permission: tournament.use
  start:
    description: start tournament.
    permission: tournament.use
  bracket:
    description: View the current tournament bracket.
  cancel:
    description: Cancel a tournament.
    permission: tournament.use
  arenas:
    description: View all currently loaded arenas.
    permission: duels.admin
  duel:
    description: Duel another player.
  event:
    description: Join the tournament world.