name: JadedDuels
version: '${project.version}'
main: net.jadedmc.jadedduels.JadedDuelsPlugin
api-version: 1.20

depend:
  - JadedCore
  - JadedChat
  - PlaceholderAPI

commands:
  arena:
    description: Runs the arena command.
  create:
    description: create tournament.
  start:
    description: start tournament.
  bracket:
    description: View the current tournament bracket.
  cancel:
    description: Cancel a tournament.